name: story_cube_app
description: "The app for the story cube gadget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  just_audio: ^0.9.46
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/assets/
